name: simple-workflow-test
on: workflow_dispatch
jobs:
  first-job:
   runs-on: ubuntu-latest
   steps:
     - name : first step
       run : first-step-start
     - name: second-step
       run: second-step-start
       
   
