name: Output Information
on: 
 pull_request:
  types:
    - opened
 workflow_dispatch:
jobs:
  info: 
   runs-on: ubuntu-latest
   environment: dev
   env: 
    WELCOME_TEXT: ${{ vars.WELCOME_TEXT }} # access env specifc variable from github
   steps:
     - name: Outupt github context
       run: | 
           echo "${{ toJSON(github) }}"
           echo "Access env variables $WELCOME_TEXT"