name: Reusable Workflow
on: workflow_call # this work flow allow to call by another work-flow
jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
    - name: Output Information
      run: echo "Deploying and uploading"